-- phpMyAdmin SQL Dump
-- version 3.3.7deb7
-- http://www.phpmyadmin.net
--
-- Host: db.inf.ufrgs.br
-- Generation Time: Jan 21, 2016 at 02:17 PM
-- Server version: 5.1.66
-- PHP Version: 5.3.3-7+squeeze19

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `mwe`
--

-- --------------------------------------------------------

--
-- Table structure for table `nctti_en_mwes`
--

CREATE TABLE IF NOT EXISTS `nctti_en_mwes` (
  `id` int(11) NOT NULL,
  `compound` varchar(250) NOT NULL,
  `source` varchar(100) NOT NULL,      
  `a_modif` varchar(100) NOT NULL,  
  `modifier` varchar(100) NOT NULL,  
  `modif_pos` varchar(100) NOT NULL,  
  `a_head` varchar(100) NOT NULL,
  `head` varchar(100) NOT NULL,  
  `number` varchar(100) NOT NULL,    
  `comp` varchar(4) NOT NULL,
  `frequkWaC` varchar(20) NOT NULL,  
  `examplesent1` text NOT NULL,
  `examplesent2` text NOT NULL,
  `examplesent3` text NOT NULL,  
  `be` varchar(20) NOT NULL,
  `have` varchar(20) NOT NULL,
  `undefdet_head` varchar(100) NOT NULL,
  `undefdet_compound` varchar(100) NOT NULL,
  `relatedto_modifier` varchar(100) NOT NULL,
  `something_modifier` varchar(100) NOT NULL,  
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (1,"health care","NEW","a","health","N","a","care","S","C","58380","His interests are effectiveness of public health interventions and the measurement of <b>health care</b> performance, including alternative medicines.","Trade unions have a clear role in the management of health and safety for <b>health care</b> workers and patients","Members of the community usually come to the hospital for a course then return to provide basic <b>health care</b> services.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (2,"wedding day","NEW","a","wedding","N","a","day","S","C","5740","The engagement period is a busy and exciting time where the betrothed couple plan their <b>wedding day</b> and prepare for married life.","All of the flowers on our cakes are handmade using sugarcraft techniques and can be kept as lasting mementos of your <b>wedding day</b>.","Each item is individually designed and handcrafted to complement the style of your dress and theme of your <b>wedding day</b>.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (3,"music festival","NEW","a","music","N","a","festival","S","C","5689","He has performed in all the great <b>music festivals</b> in Europe.","Concerts and <b>music festivals</b> are hosted at Singleton Park, Morfa Stadium and Margam Country Park.","During the eight day <b>music festival</b>, ICCM will employ musicians to perform at pitches around the city to create the festival feel.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (4,"traffic control","NEW","a","traffic","N","a","control","S","C","3982","Police were requested for <b>traffic control</b> and to remove the lorry.","Already new tramway lines systems are connected to the general <b>traffic control</b> systems and allow the tramways to run all over the city without stopping at any crossroad.","It will soon be central in air <b>traffic control</b>, guiding planes to land and take-off.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (5,"travel guide","NEW","a","travel","N","a","guide","S","C","3926","I did research, I revised a <b>travel guide</b> on Salzburg, I did some creative writing, and I also spent some time doing nothing.","Map and travel bookshop, Stanfords has a comprehensive range of world maps, <b>travel guides</b> and books.","A description often used for Antwerp in <b>travel guides</b> for backpackers.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (6,"radioactive waste","NEW","a","radioactive","J","a","waste","S","C","3406","The London Dumping Convention halted all ocean dumping of <b>radioactive waste</b>.","If you burn coal without any kind of pollution control you get large amounts of ash and sulphur (and <b>radioactive waste</b> from natural Uranium decay in the coal).","The European Community has adopted regulations on the transboundary movement of <b>radioactive wastes</b>.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (7,"information age","NEW","an","information","N","an","age","S","C","3345","Computers are playing an ever increasing role in the delivery of education and training, and are indeed the nexus of the <b>information age</b>.","How to operate in a world characterized by <b>information age</b> technology, rapid change, deepening global linkages, and the continuous unbundling of value chains.","I said that the new <b>information age</b> economy would need not less but more competition.","is","has","an","an","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (8,"love song","NEW","a","love","N","a","song","S","C","2949","The romance in Moulin Rouge breathes thanks to the <b>love songs</b> that his protagonists sing.","Give someone the ultimate romantic anniversary or valentine gift - their very own, original <b>love song</b>, written about them.","I know but this is a <b>love song</b> you could really dance to.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (9,"calendar month","NEW","a","calendar","N","a","month","S","C","2564","Bookings made within 2 <b>calendar months</b> of the holiday start date must be paid in full.","Application forms must arrive with ELCAS within one <b>calendar month</b> of the end of your chosen registration window.","Research students may begin their studies on the first day of any <b>calendar month</b>.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (10,"wedding anniversary","NEW","a","wedding","N","an","anniversary","S","C","2167","I also provide disco for engagement evenings, wedding evenings, <b>wedding anniversaries</b>, stag/hen parties.","They were presented with a card and a bottle of champagne to celebrate their 38 th <b>wedding anniversary</b>.","It's their <b>wedding anniversary</b> and he's planned a romantic night out.","is","has","an","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (11,"crime rate","NEW","a","crime","N","a","rate","S","C","2025","The <b>crime rate</b> in Australia is low, however travellers should be aware that tourists could be targeted by petty criminals.","Interestingly, there is a similar phenomenon in that the more police are employed, the higher the <b>crime rate</b>.","Kingston has the 2nd lowest <b>crime rate</b> in Greater London.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (12,"radioactive material","NEW","a","radioactive","J","a","material","S","C","1702","We are exhausting fossil fuels and using dangerous <b>radioactive materials</b> to produce energy and run cars.","But we use <b>radioactive materials</b> in medicine to treat cancers.","Doctors fear that hundreds could have been contaminated and may have ingested <b>radioactive material</b>.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (13,"world conference","NEW","a","world","N","a","conference","S","C","1584","The final report is available, and will be summarised in a paper at the 10th <b>World Conference</b> on Transport Research.","Eddie participated in several <b>world conferences</b> and was elected with the highest number of votes.","the UN also held a <b>world conference</b> on Human Rights in Vienna.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (14,"rainy season","NEW","a","rainy","J","a","season","S","C","1566","Thailand's monsoons arrive around July and last into November (the '<b>rainy season</b>').","The disease occurred in August and September, after the onset of the <b>rainy season</b>.","It is hot and humid in the summer with <b>rainy season</b> from July to September and dry season from November to April.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (15,"time difference","NEW","a","time","N","a","difference","S","C","1215","The <b>time difference</b> with the Netherlands was five hours.","Problems can be highlighted earlier and more easily, as there is no language barrier or <b>time difference</b> to deal with.","Our daughter had flown from London to Los Angeles the previous day and, despite the <b>time difference</b>, I called our son's LA home to make sure they were safe.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (16,"incubation period","NEW","an","incubation","N","a","period","S","C","1112","The <b>incubation period</b>, from exposure to the appearance of the rash, is usually 14 to 21 days.","When someone swallows bacteria that cause food poisoning, there is a delay (<b>incubation period</b>) before symptoms begin.","The <b>incubation period</b> is approximately 3-10 days whilst the duration of illness can be longer.","is","has","a","an","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (17,"civil marriage","NEW","a","civil","J","a","marriage","S","C","1058","The ban on same-sex <b>civil marriage</b> defines lesbian and gay couples as second-class citizens.","A <b>civil marriage</b> or civil partnership can be conducted in either a Register Office or an approved premise licensed by the local authority.","The restaurant also specialises in wedding receptions and is licensed for <b>civil marriage</b> ceremonies.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (18,"skin tone","NEW","a","skin","N","a","tone","S","C","1010","Choose a colour that is similar to your own <b>skin tone</b> and remember, 'less is more'.","The benefits of exercise are well known and include conditioning of the heart, lungs and muscles as well as improved <b>skin tone</b>.","I like the warm feel to the photo and the <b>skin tones</b> look natural.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (19,"winter solstice","NEW","a","winter","N","a","solstice","S","C","981","This is done at <b>winter solstice</b>, at which time darkness is maximal, and no longer increasing.","The year began at Christmas, which was anciently associated with the <b>winter solstice</b>.","Festivals were held in honour of events that were important to people's daily lives; eg, the change of seasons, harvest, and the summer and <b>winter solstices</b>.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (20,"peace talk","NEW","a","peace","N","a","talk","S","C","948","The role of China is to promote the <b>peace talk</b> process through good offices.","The cease fire comes ahead of proposed <b>peace talks</b> in the region between the two groups.","The <b>peace talks</b> were secret but he succeeded in getting some information from friendly delegates.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (21,"tear gas","NEW","a","tear","N","a","gas","S","C","872","The police surrounded us, throwing more <b>tear gas</b> and beating who ever they could catch.","The soldiers either experienced something they really objected to, or were ordered to disperse people, and suddenly <b>tear gas</b> started to fly.","He carried a nickel plated 32-caliber revolver and a <b>tear gas</b> pen as protection.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (22,"medical procedure","NEW","a","medical","J","a","procedure","S","C","793","Accidental exposures in radiotherapy continue to occur; radiation injuries continue to be caused in interventional <b>medical procedures</b>.","Dentistry, <b>medical procedures</b> and operations where conditions are unsterile are also routes of infection.","Families affected by this most common neurological condition are likely to seek any alternative <b>medical procedures</b> to reduce this high number of episodes.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (23,"marketing consultant","NEW","a","marketing","J","a","consultant","S","C","745","Our <b>marketing consultants</b> have many years experience in helping businesses market their products and services more effectively.","Full account management service with an experienced web <b>marketing consultant</b> to optimise the programme and maximise returns.","Author of two books, she now works as a freelance writer and <b>marketing consultant</b> and lives in Dartington, Devon.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (24,"peace conference","NEW","a","peace","N","a","conference","S","C","682","Geneva has historically hosted numerous <b>peace conferences</b> and initiatives for disarmament.","This report stimulated widespread discussion among the governmental representatives attending the <b>peace conference</b>.","This was confirmed at the <b>peace conference</b> when the oil companies pressed their governments to renounce all wartime promises to the Arabs.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (25,"football season","NEW","a","football","N","a","season","S","C","641","Every week of the <b>football season</b> there is always a top class football match to watch.","The Group is constructing a new 60,000 capacity stadium with a planned opening for the start of the 2006/2007 <b>football season</b>.","The 2002-2003 <b>football season</b> promises to be fascinating for football fans based in Birmingham.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (26,"computer expert","NEW","a","computer","N","an","expert","S","C","562","A computer user may call over the telephone to a <b>computer expert</b> for advice when things go wrong.","But <b>computer experts</b> warn that this new technology is susceptible to bugs, tampering and failure.","He has recently also become a <b>computer expert</b> and has been able to help with the database for the Registrations.","is","has","an","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (27,"disability insurance","NEW","a","disability","N","an","insurance","S","C","492","If you have any other unemployment or <b>disability insurance</b> to cover your mortgage payment, we will reduce your monthly benefit.","Obtain <b>disability insurance</b> quotes from the major insurance companies.","Life and <b>disability insurances</b> tend to have much longer terms, and may even, in the case of whole-of-life cover, have no renewal date.","is","has","an","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (28,"job fair","NEW","a","job","N","a","fair","S","C","473","Update your CV and visit plenty of career fairs, brush up on your interview techniques, ensure you dry-clean your best, plain suit in advance of any <b>job fairs</b>.","Summer placements are encouraged and can be found, along with permanent jobs, through the Laboratory Supporters Club annual <b>jobs fair</b>.","The Recruitment Department visits local schools, participates in <b>job fairs</b> and Job Shop week in conjunction with the Employment Service.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (29,"biological clock","NEW","a","biological","J","a","clock","S","C","467","The <b>biological clock</b> ticks — but slowly It is not so bad to delay having a first baby until your thirties, according to Professor John Mirowsky.","Closely allied to these theories is that of the <b>biological clock</b> with triggers at certain stages of development for the ageing process","In mammals, the <b>biological clock</b> is controlled from the suprachaismatic nucleus (SCN), an area of the brain in the hypothalamus.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (30,"day shift","NEW","a","day","N","a","shift","S","C","455","A working week of seven days was divided into two shifts: a <b>day shift</b> of three to four hours and a night shift which lasted from 10pm until dawn.","Gillian particularly likes the <b>day shifts</b> as she gets to spend more time with the residents.","On the <b>day shift</b> on alternate weeks, we were confined to barracks on a Tuesday evening.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (31,"noise complaint","NEW","a","noise","N","a","complaint","S","C","446","Some of the <b>noise complaints</b> I get relate to incoming planes.","However, in the absence of <b>noise complaints</b>, it had to be concluded that there was no serious source of noise emanating from the premises.","The council's noise service investigate a wide range of <b>noise complaints</b> from a variety of sources.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (32,"music journalist","NEW","a","music","N","a","journalist","S","C","371","He later became a <b>music journalist</b> covering the new wave and punk rock explosion, his interviews with The Clash, Sex Pistols and Blondie making him a cult figure.","James is a well established <b>music journalist</b> who clearly knows his stuff and admires his subject.","Other guest speakers include <b>music journalist</b> and radio presenter Steve Lamacq, music industry lawyer Helen Searle, whose clients include Jamiroquai and Moby.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (33,"bankruptcy proceeding","NEW","a","bankruptcy","N","a","proceeding","S","C","370","The official receivers costs take priority over sums due to a trustee in the <b>bankruptcy proceedings</b>.","Geoffrey Richmond was today the subject of <b>bankruptcy proceedings</b> at Leeds Crown Court with debts of around £ 3.3 million following the collapse of a business.","They are aware that funds/assets in the <b>bankruptcy proceedings</b> cannot be made available for the payment of their fees.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (34,"cocoa butter","NEW","a","cocoa","N","a","butter","S","C","352","Enriched with <b>cocoa butter</b> it will leave the skin feeling silky smooth.","Hear all about the fascinating stages of chocolate making, sample different cocoa beans and <b>cocoa butter</b>.","The basic ingredients used to make every one of Trevarno's soaps are olive oil, palm oil, coconut oil and <b>cocoa butter</b>.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (35,"box office","NEW","a","box","N","a","office","S","NC","14729","Arguably the King of Comedy for the last ten years, Jim Carrey is <b>box office</b> gold.","Angel Heart was a critical and <b>box office</b> success - two facets that strongly contrasted with Adrian Lyne's Jacob's Ladder.","As a movie, it would be forgettable, but the social furore has guaranteed <b>box office</b> buoyancy and discussion.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (36,"big picture","NEW","a","big","J","a","picture","S","NC","6647","Whilst we're relieved that this is the outcome of the Chancellor's deliberations over UK Sports' proposals, the Government also has to look at the <b>bigger picture</b>.","Going to India has made me much more confident and self-assured and also opened my eyes to the much <b>bigger picture</b>.","Don't become so wrapped up in schemes or projects that you take your eye off the <b>bigger picture</b>","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (37,"grass root","NEW","a","grass","N","a","root","S","NC","3752","I have asked the Arts Council to develop strategies to recognise the importance of community, <b>grass roots</b> activity in developing the arts in Wales.","If we define micro credit in literal sense of the term, it means a small amount sanctioned to poor at the <b>grass root</b> level irrespective of the geographical location","The welfare oriented transformation of the poor clients through micro finance calls for an appropriate tool for reflecting the reality of the life situation at <b>grass root</b> level.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (38,"black box","NEW","a","black","J","a","box","S","NC","3140","Smart sensors are sold as <b>black boxes</b> despite the fact that their safety justification might require knowledge of their internal structure and development process.","My marriage had exploded in midair, and all I could do was search the rubble for some sign of a probable cause, some telltale <b>black box</b>.","If the <b>black box</b> flight recorder is never damaged during a plane crash, why is n't the whole aeroplane made out of the stuff?","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (39,"cable car","NEW","a","cable","N","a","car","S","NC","2559","Here you have a choice - it is either 588 steps down or take the <b>cable car</b>.","I pestered the owners if the <b>cable car</b> was running, finding it hard to believe them, but eventually accepting the fact that it was.","Every day offers a new and exciting trip as <b>cable cars</b> and funicular railways transport you throughout the region with absolute Swiss precision.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (40,"low profile","NEW","a","low","J","a","profile","S","NC","2517","If you are a freelance, you could send your details and thus get some <b>low profile</b> publicity for a very low fee - free, in fact.","I've written the guestbook myself in asp and it was the shock that someone was targeting my <b>low profile</b> site which I found a bit creepy.","Some 7,000 police officers were on call but security forces kept a <b>low profile</b> along the rally's route.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (41,"shelf life","NEW","a","shelf","N","a","life","S","NC","2401","It's done merely to maintain the visual appearance and extend the <b>shelf life</b>.","Packaged parts naturally have a shorter <b>shelf life</b> than bare die; we can store your silicon for you and produce the packaged product on demand thus enhancing the overall longevity and reliability of your parts.","Before the days of refrigeration, milk was usually processed on the farm to give it a longer <b>shelf life</b> and provide a cash income.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (42,"dark horse","NEW","a","dark","J","a","horse","S","NC","1102","Then there is the real <b>dark horse</b>, Italy, in the midst of a national crisis.","She was the favourite, with the erratic but occasionally brilliant Cuban runner Aurelia Pento, the <b>dark horse</b>.","We could be a <b>dark horse</b> for the World Cup in 12 months time, and not do as badly as some people expect us to.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (43,"hard shoulder","NEW","a","hard","J","a","shoulder","S","NC","1090","Be aware that other vehicles may be stationary on the <b>hard shoulder</b>.","<b>Hard shoulders</b> can be converted for use by traffic in only two years, compared with up to ten years to plan and construct additional lanes.","We think <b>hard shoulders</b> are essential for the safety of motorists who have broken down and to allow emergency services to get to the scene of accidents quickly.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (44,"hot potato","NEW","a","hot","J","a","potato","S","NC","913","The pipeline is set to create a human rights disaster in the region, and has become such a political <b>hot potato</b> that the Bank has postponed the decision.","As the public become more educated about risk, the level at which the state pays and at which the individual pays will become a <b>hot potato</b>.","All political <b>hot potatoes</b> in their time but now accepted as just a normal part of a healthy democratic debate.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (45,"glass ceiling","NEW","a","glass","N","a","ceiling","S","NC","846","Women are continuing to slowly break through the <b>glass ceiling</b> of UK business and increase their company's profitability, according to new research.","Described as \" the woman who cracked the BBC's <b>glass ceiling</b> \", she has recently published her autobiography under the title of Woman of Today.","If a woman fails to get promoted, she's hit the ' <b>Glass Ceiling</b> '.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (46,"double whammy","NEW","a","double","J","a","whammy","S","NC","735","CPRE points out that the countryside is facing a <b>double whammy</b> with traffic levels rising faster on rural than urban roads, while the reduction in road accidents is slower{3 }.","Iraqi civilians face a murderous <b>double whammy</b>: they are victims of state terrorism conducted by the US and Britain as well as home-grown acts of violence.","The <b>double whammy</b> here is that the nurse's investigation takes place in a drama therapy session taken by a patient who was once an acclaimed actress.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (47,"pipe dream","NEW","a","pipe","N","a","dream","S","NC","634","The Party's vision of an independent, socialist Scotland is fast becoming a <b>pipe dream</b>.","Are these plans the <b>pipe dreams</b> of self-aggrandising bureaucrats?","The result is that whether you sleep on your back or your side, the ultimate night's sleep is no longer a <b>pipe dream</b>.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (48,"brain drain","NEW","a","brain","N","a","drain","S","NC","618","This <b>brain drain</b> exacerbates the situation for those staying behind, as it leads to a loss of skills which are then not to be passed on to the next generation.","A flow of scientists in both directions between the US and Europe would make the perceived \" <b>brain drain</b> \" of researchers to the former much less of a problem.","We are suffering a chronic \" <b>brain drain</b> \" as qualified people leave for greener pastures abroad.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (49,"blind alley","NEW","a","blind","J","an","alley","S","NC","566","The science of economics has been led up a <b>blind alley</b> by theories that have made it seem increasingly remote and unreal to anyone outside the academic community.","There have been several <b>blind alleys</b> and wrong turnings, but the company's progress has generally been true to the original concept.","Mathematical problem solving involves going down lots of <b>blind alleys</b>, experimenting with different directions until the solution is found.","is","has","an","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (50,"blue print","NEW","a","blue","J","a","print","S","NC","497","Our free health check will give you the <b>blue print</b> to identify, select and measure the key metrics to enable you to better manage your service delivery.","Projects of reclamation both connect us in a struggle for social justice and also provide a <b>blue print</b> for more dynamic modes of existence.","An architectures isn't a <b>blue print</b> for designing a single systems, but a framework for designing a range of systems over time.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (51,"white spirit","NEW","a","white","J","a","spirit","S","NC","461","Then wash again using <b>white spirit</b> and steel wool.","This is very hard wearing but gives off a strong odour and brushes can only be washed in <b>white spirit</b>.","The varnish layer was removed with mixtures of acetone and acetone in <b>white spirit</b>.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (52,"smoke screen","NEW","a","smoke","N","a","screen","S","NC","437","Escorting coastal craft and aircraft produced <b>smoke screens</b> to mask sweeping operations.","Some of us think that a lot of it is a <b>smoke screen</b> for a much wider operation.","Myths have become popularly known as <b>smoke screens</b> and are largely being peddled by the anti-GMO activists.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (53,"big cheese","NEW","a","big","J","a","cheese","S","NC","353","We talk to the (normally reclusive) <b>big cheese</b> about his journey from stall owner to taking on the big guns at HMV.","After a ridiculous wait while police were deployed and the plebs pushed back, out popped Uefa <b>big cheese</b> Lennart Johannson.","I've just spent a week trawling round Silicon Valley, talking to a mix of developers, entrepreneurs, venture capitalists, industry observers and <b>big cheeses</b> from well established companies.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (54,"basket case","NEW","a","basket","N","a","case","S","NC","352","Now Iraq is a <b>basket case</b>, the US is all but defeated by the resistance, and the threat of islamist terrorism is greater than ever.","I'd forgotten what a <b>basket case</b> i am at the end of pregnancy (mind you, last time i was for the whole 9 months!","Africa, in other words, is a <b>basket case</b>, there just to be exploited economically and militarily.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (55,"double cross","NEW","a","double","J","a","cross","S","NC","334","The epsiode \" Gambit \" is a fantastic episode full of plotting, sub plotting, betrayal, <b>double crossing</b>, a game of chess, and the BBC costume departement going wild!","Out of her league and desperate, Laurel is forced to accept help from the very man who is trying to ensnare her father in his own web of <b>double crosses</b>.","There are also other characters with their own agendas, and very soon there's a host of <b>double crosses</b> amidst hails of gunfire and pyrotechnic mayhem.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (56,"damp squib","NEW","a","damp","J","a","squib","S","NC","330","It was probably just a bit too much for everyone in the end and it finished in a <b>damp squib</b>, but we always said we were building for next season.","The important thing is to manage it well, ensure the season does n't fizzle out into a <b>damp squib</b> as it did after our cup run two years ago.","During this time the political environment has provided both <b>damp squibs</b> and powerful rockets.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (57,"banana republic","NEW","a","banana","N","a","republic","S","NC","297","The result is our roads are more congested than ever before; so congested, indeed, that we seem less like the world's fourth-largest economy and more like the most inept <b>banana republic</b>.","As Britain grinds to a halt amidst rail chaos, fuel shortages and floods, the head of the CBI brands Britain as being \" like a <b>banana republic</b> \"!","My point is in the past historians referred to the Central American countries as <b>banana republics</b>, implying these are countries, nations with governments without any dignity.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (58,"blue blood","NEW","a","blue","J","a","blood","S","NC","179","The Cloister attracted vacationing <b>blue bloods</b>, drawn by its old world ambience - the Coolidges, the Eisenhowers and Carters would come to play bingo in the lounge and dance the cha-cha in the ballroom.","In fact she had seriously <b>blue blood</b> flowing in her veins and had important dynastic links with the royal family itself.","European <b>blue bloods</b>, in particular Britain's Royal Family who were related to the Russian Imperial house, did all they could to aid their overthrow.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (59,"double Dutch","NEW","a","double","J","a","Dutch","S","NC","173","But I imagine that if you agree to do a role like that you must know the territory in some way, otherwise it would feel like <b>double dutch</b>.","If any of the terms used below sound like <b>double Dutch</b> to you then visit our Cyberspeak Glossary where most terms will be explained.","It makes no sense to me at all; it sounds like <b>Double Dutch</b> or Latin or something.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (60,"dream ticket","NEW","a","dream","N","a","ticket","S","NC","168","Two years later Wolstenholme was given his <b>dream ticket</b> when the BBC used its cameras for the World Cup Finals in England.","Clarke and Cameron are neck and neck, prompting pressure for them to combine in a ' <b>dream ticket</b> '.","If I can get all this and it can also be organic, then that is my <b>dream ticket</b>.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (61,"head hunter","NEW","a","head","N","a","hunter","S","NC","142","Local recruitment agents and <b>head hunters</b> post vacancies for Milton Keynes, Witney, Skegness and Felixstowe.","For a <b>head hunter</b>, networking is all about visibility and profile.","Most of these appointments are advertised and <b>head hunters</b> are often involved too.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (62,"big wig","NEW","a","big","J","a","wig","S","NC","137","To secure promotion you have to impress your employers, the suits on high, the <b>big wigs</b>, and the fat cats.","The popstar turned DJ has been booked as a panellist on the BBC's Question Time, a slot more usually reserved for political <b>big wigs</b> and the like.","He was married three times, was a mason, a championship level clay pigeon shooter and a <b>big wig</b> in the local tory party.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (63,"blood bath","NEW","a","blood","N","a","bath","S","NC","132","Is this the first blow in the upcoming civil war, and the <b>blood bath</b> which may follow?","What was meant to be the perfect crime turns into a nasty gang war resulting in a <b>blood bath</b> on the glorious streets of 1950s Paris.","Kurds now stuck in Kirkuk fear the same kind of <b>blood bath</b> if Iraqi troops decide to stand and fight any U.S. military assault on the city, Ali said.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (64,"sugar daddy","NEW","a","sugar","N","a","daddy","S","NC","126","It is only polite that she doesn't start treating me like some sort of <b>sugar daddy</b>.","This kind of luxury doesn't come cheap, but if ever there was a reason to go trawling for a City <b>sugar daddy</b>, this place is it.","Not only am I going to marry Ewan McGregor and Javier Bardem, but Eastwood would make a wonderful <b>Sugar Daddy</b>.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (65,"backroom boy","NEW","a","backroom","N","a","boy","S","NC","109","There are lots of technical and scientific staff whom you never see who are deeply involved in your disease: they often get forgotten as ' <b>backroom boys</b> and girls '","Cecil Milner was a respected <b>backroom boy</b> in London music circles, arranging for many top orchestras such as Mantovani, for whom he supplied around 220 scores.","Translators are often thought of as <b>backroom boys</b> and girls who keep out of the limelight.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (66,"poison pill","NEW","a","poison","N","a","pill","S","NC","102","Allowing young people to opt out of the basic state pension is giving them a <b>poison pill</b>.","Fearing a possible fallout with the shareholders, Rupert Murdoch designed a <b>poison pill</b> to keep control of the company in the family hands.","News Corp also announced it had extended a defensive \" <b>poison pill</b> \" measure to prevent attempts to gain control of the company for a further two years.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (67,"heavy cross","NEW","a","heavy","J","a","cross","S","NC","73","Having to pay back university top-up fees is a <b>heavy cross</b> to carry, especially for those graduates from less well-off homes.","In this fallen world we may have a very <b>heavy cross</b> to carry.","Her presentation gave the impression of being yet another masterclass on gold-plating regulations, and so creating more jobs for bureaucrats and a <b>heavier cross</b> for farmers to bear.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (68,"hard drive","NEW","a","hard","J","a","drive","S","PC","19008","A faster CPU or a faster <b>hard drive</b> might speed up suspend and resume.","A good option is to add a second <b>hard drive</b> and dedicate it to storing digital audio recordings.","All these temporary files will slow down your computer, take up space on your <b>hard drive</b> (memory).","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (69,"fairy tale","NEW","a","fairy","N","a","tale","S","PC","5107","Her dresses are those you would find in <b>fairy tales</b>.","I loved my father's old <b>fairy tale</b> books.","In <b>fairy tales</b> we can experience those lives and adventures.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (70,"fresh water","NEW","a","fresh","J","a","water","S","PC","5026","Backford Brook is one of the few <b>fresh water</b> streams in the area.","Finally, increased <b>fresh water</b> from melting glaciers and sea ice could alter ocean circulation patterns and destabilize regional climate patterns.","Always make sure to provide plenty of <b>fresh water</b> for your kitty, and it does n't hurt to add water to wet food that your cat may be used to eating.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (71,"field work","NEW","a","field","N","a","work","S","PC","3868","<b>Field work</b> and practical archaeology are a particular focus.","The arbitrary removal of metal objects from the ground inevitably will jeopardise both present and future <b>field work</b>.","He spent time on the Island carrying out <b>field work</b> for his book","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (72,"fair play","NEW","a","fair","N","a","play","S","PC","3243","But attitudes of kindness, <b>fair play</b>, loyalty, honesty, etc could not by definition be principles, and were simply sentimental notions.","<b>Fair play</b> incorporates the concepts of friendship, respect for others and always playing in the right spirit.","But free trade, as practised within nations, has many restraints on it to ensure justice and <b>fair play</b>.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (73,"contact lenses","NEW","a","contact","N","","lenses","P","PC","3202","Yes there are various options available to you to correct your astigmatism with <b>contact lenses</b>.","<b>Contact lenses</b> are preferrable to glasses to aid looking through the eyepiece, if applicable.","In recent years most of the pathophysiology of dry eye and the pathogenesis of corneal infections are associated with <b>contact lens</b> wear.","are","have","","<!--X-->","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (74,"academy award","NEW","an","academy","N","an","award","S","PC","2722","Lardner shared an <b>Academy Award</b> for best original screenplay with Michael Kanin in 1942 for Woman of the Year","<b>Academy Award</b> winner Whoopi Goldberg (Ghost) stars as a sassy lounge singer forced to hide in a quiet convent.","Bette Davis, Ernest Hall and Victor Buono received <b>Academy Award</b> nominations, while Norma Koch took home an Oscar for the costume design.","is","has","an","an","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (75,"traffic jam","NEW","a","traffic","N","a","jam","S","PC","2622","But then picture him trying to drive through the <b>traffic jam</b> on Sunday morning in downtown Austin.","We got stuck in a <b>traffic jam</b> caused by a crash during rush hour and arrived just before lunch.","A further advantage of on-site accommodation is that guests can avoid the <b>traffic jams</b> which blight the city.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (76,"injury time","NEW","an","injury","N","a","time","S","PC","1669","Sam was replaced in <b>injury time</b> having just missed a try scoring opportunity.","The final play of the match came in <b>injury time</b> as Rangers kept the ball in the Falkirk half.","He mysteriously awarded the visitors a free kick, and then an undeserved corner, in <b>injury time</b>.","is","has","a","an","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (77,"arcade game","NEW","an","arcade","N","a","game","S","PC","1639","The monkey in the game is King Kong and it is another version of the classic <b>arcade game</b> Donkey Kong.","In an ordinary <b>arcade game</b> the effect is created through a need to destroy aliens and make a high score.","Pac-Man - Play the most popular <b>arcade game</b> of all time!","is","has","a","an","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (78,"stag night","NEW","a","stag","N","a","night","S","PC","1522","Although it is traditionally the best man's responsibility to organise the <b>stag night</b> it is ultimately the groom's decision as to where he wants to spend it and whom he wants to invite.","We have been organising <b>stag nights</b>, parties and weekends for a long time now but we'll never grow bored of it!","One of your roles is to help the best man prepare the <b>stag night</b>.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (79,"hen party","NEW","a","hen","N","a","party","S","PC","1479","You can spot the stag and <b>hen parties</b> easily because they always dress in stupid outfits or matching T-shirts with their names printed on.","Torquay offers excellent nightlife, and is extremely popular as a stag weekend break, and <b>hen parties</b>!","We supply the lighting, sound, music, posters and tickets and some of the best <b>hen party</b> performers on the cabaret scene in the UK and Europe.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (80,"pain killer","NEW","a","pain","N","a","killer","S","PC","1040","There may be symptoms such as bleeding or persistent pain not relieved by simple <b>pain killers</b>.","Rheumatoid arthritis should be treated by a doctor who would start with anti-inflammatory <b>pain killers</b> such as ibuprofen.","Often there is a chronic shortage of medicine, of <b>pain killers</b>, even of anaesthetics.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (81,"jet lag","NEW","a","jet","N","a","lag","S","PC","1017","My first morning there I got up at 6am and decided to take a walk to help me get over my <b>jet lag</b>.","This is similar to <b>jet lag</b>, where rapid travel between time zones means that you find yourself awake when everybody else is asleep","<b>Jet lag</b> is not a problem as long as you catch some sleep during the flight.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (82,"ghost town","NEW","a","ghost","N","a","town","S","PC","1013","The town centre is now deserted - it's almost like a <b>ghost town</b>!","Dilapidated Virginia City of old silver boom days is determined not to become a <b>ghost town</b>.","With the mines closing down in the early 1990's it tumbled into the darkness of a small quiet <b>ghost town</b>.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (83,"white noise","NEW","a","white","J","a","noise","S","PC","989","There are a number of sound effects such as siren, telephone, electric shock and <b>white noise</b>.","If you try to transmit, in digital mode, into an analog repeater, all the analog radios on the repeater will simply hear <b>white noise</b>.","<b>White noise</b> is a mixture of all frequencies just as white light is a mixture all wavelengths (colours) of light.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (84,"home run","NEW","a","home","N","a","run","S","PC","963","ou can't hit a <b>home run</b> every time up at bat, but at least I want to show that I 'm trying my best.","The series showcased rookie Willie McGee hitting two <b>home runs</b> in game 3, still tied as a record for rookies.","The star of Olympic baseball has been Orestes Kindelan Olivares who established a Games record of nine <b>home runs</b> in nine games.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (85,"leap year","NEW","a","leap","N","a","year","S","PC","842","It comprises 12 months of 30 days, plus 5 days (6 in a <b>leap year</b>); each month has 3 decades of 10 days.","To correct this, every 100th year (but not every 400th year) was excluded as a <b>leap year</b>.","This way of reckoning <b>leap years</b>, which we use today, is the Gregorian Calendar.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (86,"social insurance","NEW","a","social","J","an","insurance","S","PC","841","<b>Social insurance</b> and national assistance organised by the State are designed to guarantee, on condition of service, a basic income for subsistence.","The Ministry is responsible for health, social welfare, environmental health, safety at work, <b>social insurance</b>, insurance, family, and gender equality.","There is strong support (especially among the well off) for a <b>social insurance</b> system based on the principle of solidarity and accountability.","is","has","an","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (87,"speed trap","NEW","a","speed","N","a","trap","S","PC","573","The organisation responsible for the <b>speed trap</b> in Derby refused to bow to pressure from outraged motorists caught on camera.","They are very accurate and means that the police can set up a <b>speed trap</b> in a matter of moments.","Anstey had passed through the <b>speed trap</b> at 188 mph (300.6 km/h).","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (88,"best man","NEW","a","best","J","a","man","S","PC","519","All stories aside Neil is a great mate and it made me extremely proud to be asked to be his <b>best man</b> ","At this unique event the promoter and his bride were married live onstage with Grooverider as <b>best man</b>.","A <b>best man</b> speech should be like a mini skirt, short enough to be interesting, but long enough to cover the essentials","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (89,"bull market","NEW","a","bull","N","a","market","S","PC","389","Taking out the recent <b>bull market</b>, however, it did not even double in value in the 25 years to 1994.","The three year <b>bull market</b> in equities has certainly boosted the fortunes of these companies by increasing the value of their assets.","The Directors consider that uranium is in the early stages of a secular <b>bull market</b>.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (90,"bad apple","NEW","a","bad","J","an","apple","S","PC","337","The problem for them, of course, is how to explain how these few <b>bad apples</b> managed to stay in place for so many years.","However it's the same old story: a few <b>bad apples</b> and we all get it in the neck!","However, it will not work unless every single person does it, because one <b>bad apple</b> ruins the whole barrel.","is","has","an","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (91,"fall guy","NEW","a","fall","N","a","guy","S","PC","264","And though the Chairman and Chief Executive have been the <b>fall guys</b>, much of the blame that has been placed upon them is a little unfair.","However, sadly and a bit arbitrarily, it seems tidal streams have now been selected as the <b>fall guy</b>.","Alan Johnson is the Government's new <b>fall guy</b> for pensions-related incompetence.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (92,"insider trading","NEW","an","insider","N","a","trading","S","PC","251","The Securities Commission of New Zealand has settled its proceedings alleging <b>insider trading</b> at Provenco, the technology company.","They detect a sizeable impact of <b>insider trading</b> on market volatility.","Players can engage in stock manipulation, corporate raiding and <b>insider trading</b> to take advantage of their opponents and win the day!","is","has","a","an","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (93,"rice paper","NEW","a","rice","N","a","paper","S","PC","222","<b>Rice paper</b> is a thinner paper and <b>rice paper</b> is also used in the manufacture of Chinese and Japanese lanterns.","The result is monochromatic nude self-portraits produced with Chinese ink on <b>rice paper</b>.","And we had to explain to her the difference between <b>rice paper</b> and ordinary paper.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (94,"copy cat","NEW","a","copy","N","a","cat","S","PC","210","We're sure the competition is working hard on releasing <b>copy cat</b> products.","If they got the Ripper, the crimes of the <b>copy cat</b> could be dealt with easily.","This is why many men that use the <b>copy cat</b> products do not get the same relief.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (95,"Freudian slip","NEW","a","Freudian","J","a","slip","S","PC","163","Well it wasn't a mistake or a <b>Freudian slip</b> of the finger...y'see the Senators site is also supposedly using unlicenced software!","Indicators of defences against anxiety (or other conflict in the psyche), include \" <b>Freudian slips</b> \", denial, \" behaving strangely \", impatience, dreams and fantasies.","Although administration officials would later prevail on the president to try and shoot more from the brain than the hip, his <b>Freudian slip</b> had revealed the contextual frame in which the US would respond.","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (96,"Dutch courage","NEW","a","Dutch","J","a","courage","S","PC","158","We had to go down to the pub to get some <b>Dutch courage</b>!","We suggest you try the following cocktail to work up a bit of <b>Dutch courage</b> to get you through the match!","After some <b>Dutch courage</b> (a few vodkas) in the nightclub, and a nerve-racking conversation, we kissed!","is","has","a","a","<!--X-->","something");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (97,"beauty sleep","NEW","a","beauty","N","a","sleep","S","PC","115","He obviously felt deprived of his <b>beauty sleep</b>, and had bags under his eyes.","Get into the habit or regularly exfoliating your skin and drinking lots of water and making sure you get your <b>beauty sleep</b>.","Dudley awoke from his <b>beauty sleep</b> with a ferocious appetite.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (98,"baby blues","NEW","a","baby","N","a","blues","S","PC","74","While as many as 80 % of mothers experience a temporary and mild condition referred to as the <b>baby blues</b>, up to 15 % of women have the more severe reaction you're experiencing.","This condition is different form the few days of weepiness called the <b>Baby Blues</b>.","<b>Baby Blues</b> is based on a true story, exposing the problems created by puerperal psychosis; deep clinical depression that sometimes follows childbirth.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (99,"honey trap","NEW","a","honey","N","a","trap","S","PC","47","By planting a local weed (napier grass), pests are lured away from the corn into a <b>honey trap</b>.","Prices are what you would expect in a tourist <b>honey trap</b>.","The son of the Cabinet Minister was at the centre of a cannabis <b>honey trap</b>.","is","has","a","a","related to","<!--X-->");
INSERT INTO nctti_en_mwes(id, compound,source,a_modif,modifier,modif_pos,a_head,head,number,comp,frequkWaC,examplesent1,examplesent2,examplesent3,be,have,undefdet_head,undefdet_compound,relatedto_modifier,something_modifier) VALUES (100,"black operation","NEW","a","black","J","an","operation","S","PC","35","On the one hand the CIA acquired $4 billion for use in future <b>black operations</b>.","Israel has been running its own <b>black operations</b> with the help of Kurds it has trained.","Lansdale's job was to provide \"actors\" for certain <b>black operations</b> deployed by the covert operatives.","is","has","an","a","<!--X-->","something");
